### ISSUE TITLE
Normalize format of amendments to E212_MNC

### ISSUE THREAD

**Issue by strogonoff** [ituob/itu-ob-data#27]
E212 amendment format so far seems pretty straightforward (see https://www.ituob.org/messages/amending-sp%20E212_MNC%20(2018-12-15)/).

Typed version:

```typescript
type Operation = 'ADD' | 'SUP' | 'LIR' | 'PAR' | 'P'

type E212MNCAmendmentRecord {
	operation: Operation,

	country: string,

	// MCC+MNC. Sequence of numbers separated by a space. May be normalized into two number fields
	mccMnc: string, 

	// Operator/Network
	operator: string,
}

type E212MNCAmendment = { contents: E212MNCAmendmentRecord[] }
```

**Comment by strogonoff** [comment]
@ronaldtse can we confirm that a given MCC + MNC combination (e.g., `412 01`) is and always will be globally unique? Useful to know whether it can be considered primary key/index in the overall data structure.

Latest E.212 MNC document, for example: https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.212B-2018-PDF-E.pdf

**Comment by strogonoff** [comment]
@ronaldtse  In this document, can we clarify data structure in section _Shared Mobile Country Codes (MCC) for other purposes and their respective Mobile Network Codes (MNC)_ (closer to the end of the document)? It seems to be a new addition.

Questions as follows:

* The first column of the table: what would be the most appropriate title for it? What kind of information can it contain? Is first column always going to have a value for each code, or can one value span multiple codes?

* Why is code 902 01 not part of previous section (_Shared Mobile Country Codes (MCC) for networks and their respective Mobile Network Codes (MNC)_)? It seems to be just a regular shared code.

Not trying to pry into their affairs, but understanding their reasoning will help us get the structure right.

**Comment by strogonoff** [comment]
@ronaldtse Is this something they can help with? Ramping work on ITU OB editor app again, it’d be helpful to know our message formats

**Comment by strogonoff** [comment]
* Message editor: https://github.com/ituob/itu-ob-editor/issues/5
* Message output on ituob.org: https://github.com/ituob/ituob.org/issues/22
* Data migration for existing edition data will be done per this issue

**Comment by strogonoff** [comment]
Normalizing amendment format after the dataset itself is normalized.

Following are two approaches to normalizing both.

**Comment by strogonoff** [comment]
# Approach 1, principled

This approach is strongly normalized.

## Examples

### Dataset

```yaml
E212_MNC:
  280 02:
    *:
      area: Cyprus
      network: CYTA
  208 01:
    "0000000000-0099999999; 0200000000-9999999999":
      area: France
      network: Orange
    "0100000000-0199999999":
      area: Monaco
      network: Orange/Monaco Télécom
  901 03:
    *:
      area: shared
      network: Iridium Communications Inc
  902 01:
    *:
      area: shared
      special: shared code
      network: MulteFire Alliance
```

### Amendment (example based on OB edition 1173)

```yaml
amendments:
  E212_MNC:
    280 23:
    280 02:
      *:
        area: Cyprus
        network: CYTA
```

## Format specs

### Dataset

```typescript
interface MSINRangeData {
  [msinRange: string]: {
    area: string,
    network: string,
  }
}
interface MNCDataset {
  [mncCode: string]: MSINRangeData,
}
```

Where:

* `mncCode` is a string in the form of `280 02`
* `msinRange` is a string such as `"0000000000-0099999999; 0200000000-9999999999"`, or `"*"` meaning all MSIN values within this MNC code

### Amendment

```typescript
interface MNCDatasetAmendment {
  [mncCode: string]: MSINRangeData | undefined,
}
```

* Amendment “diff” mimics dataset structure. Where a record is removed / revoked, MNC code points to nothing (`undefined`). Otherwise it points to a MSINRangeData, same as in the dataset.
* The burden of formatting this amendment data into human-readable SUP/ADD/LIR/PAR records is on compilation/build routine.
* If an already existing MNC code data is specified in the amendment, the build would calculate the difference from preceding dataset version, and use the appropriate amendment code.

**Comment by strogonoff** [comment]
# Approach 2

This one mimics how dataset is distributed in DOC/PDF formats currently.

## Examples

### Dataset

```yaml
E212_MNC:
  geographical:
    Cyprus:
      280 23:
        network: CYTA
    France:
      208 01:
        network: Orange
    Monaco:
      208 01:
        network: Orange/Monaco Télécom

  shared:
    901 03:
      network: Iridium Communications Inc

  other:
    902 01:
      network: MultiFire Alliance
      purpose: shared code

  extra_territorial:
    208 01:
      - area: France
        network: Orange
        msin_ranges: "0000000000-0099999999; 0200000000-9999999999"
      - area: Monaco
        network: Orange/Monaco Télécom
        msin_ranges: "0100000000-0199999999"
```

### Amendment

```yaml
amendments:
  E212_MNC:
    geographical:
      Cyprus:
        - SUP:
          280 23:
            network: Mundio Mobile Cyprus Ltd
        - ADD:
          280 02:
            network: CYTA
```
