### ISSUE TITLE
Issue 1117 contains empty Q708_ISPC content

### ISSUE THREAD

**Issue by ronaldtse** [ituob/itu-ob-data#46]
The 1117 issue `amendments.yaml` is missing Q.708 ISPC content:

```
  - type: amendment
    target:
      publication: Q708_ISPC
    contents: {}
```

This was raised during the site building process of www.ituob.org.
