### ISSUE TITLE
Amendments for R_SP_LM.V and R_SP_LN.VIII take "year" as `position_on`, not a full date

### ISSUE THREAD

**Issue by ronaldtse** [ituob/itu-ob-data#47]
They should be:

```yaml
  - type: amendment
    target:
      publication: R_SP_LN.VIII
      position_on: 2016
```

And
```yaml
  - type: amendment
    target:
      publication: R_SP_LM.V
      position_on: 2019
```

But since ituob.org currently does not support `position_on:` being a year, we temporarily changed these into full dates, i.e. January 1 of that year.

This task is to revert those changes once ituob.org supports them.
